#!/bin/bash

# Source and destination directories
SOURCE_DIR="/var/opt/app/media/datapipe_attachments"
DEST_DIR="/var/opt/airflow/manual_uploaded_files"

# Get the current date (without time)
CURRENT_DATE=$(date '+%Y_%m_%d')

# Filename pattern (matching any time on the current date)
FILENAME_PATTERN="attachments_${CURRENT_DATE}_*.xlsx"
FILENAME_PATTERN_CSV="attachments_${CURRENT_DATE}_*.csv"

# Check for .xlsx files
for FILE in ${SOURCE_DIR}/${FILENAME_PATTERN}; do
  if [ -f "$FILE" ]; then
    FILENAME=$(basename "$FILE")
    cp "$FILE" "${DEST_DIR}/$FILENAME"
    if [ $? -eq 0 ]; then
      echo "File $FILENAME copied successfully."
    else
      echo "Failed to copy the file $FILENAME."
    fi
  else
    echo "No file found matching the pattern $FILENAME_PATTERN."
  fi
done

# Check for .csv files
for FILE in ${SOURCE_DIR}/${FILENAME_PATTERN_CSV}; do
  if [ -f "$FILE" ]; then
    FILENAME=$(basename "$FILE")
    cp "$FILE" "${DEST_DIR}/$FILENAME"
    if [ $? -eq 0 ]; then
      echo "File $FILENAME copied successfully."
    else
      echo "Failed to copy the file $FILENAME."
    fi
  else
    echo "No file found matching the pattern $FILENAME_PATTERN_CSV."
  fi
done
